services:
  app:
    build: .
    command: node app.js
    env_file:
      - .env
    environment:
     - URI=mongodb://root:example@mongodb/
    ports:
      - 8080:8080

  mongodb:
    image: mongo:6.0.5
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
    - "27017:27017"
